version: '3'
services:

  db-movie:
    container_name: db-movie
    build: db
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}

  app-movie:
    container_name: app-movie
    build:
      context: app
      args:
        appuser: ${APP_USER}
    depends_on:
      - db-movie
