version: '3'
services:
  db-movie:
    build: db
    container_name: db-movie
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    hostname: db-movie
    volumes:
      - pg-data-movie:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always
  app-movie:
    build:
      context: app
      target: prod
      args:
        appuser: ${APP_USER}
    container_name: app-movie
    hostname: app-movie
    volumes:
      - app-static:/app/static
      - app-media:/app/media
    depends_on:
      - db-movie
    env_file: .env.prod
    expose:
      - "8000"
    restart: unless-stopped
#
  nginx:
    build: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - app-static:/static
      - app-media:/media
    depends_on:
      - app-movie
    ports:
      - "80:80"

volumes:
  pg-data-movie:
  app-static:
  app-media: